// Generated by Wrangler
// After adding bindings to `wrangler.jsonc`, regenerate this interface via `npm run cf-typegen`
interface Env {
  // Worker AI binding
  AI: any;
  
  // Browser Rendering API for searching images
  BROWSER: Fetcher;
  
  // KV namespace for caching results
  ART_CACHE: KVNamespace;
  
  // Durable Object for the agent
  CHRISTIAN_ART_AGENT: AgentNamespace<ChristianArtAgent>;
}